### PR TITLE
added some warnings to the Mahti and Narvi users in DDP pytorch

### PR DESCRIPTION
**Pull request by Blade6570**
In Mahti the DDP hangs with the current setup. Added a workaround for now. More investigation needed. 
In Narvi for some nodes, the training does not start due to erroneous IP. Fixed it now

### CODE REVIEW

**Comment by v-iashin** [comment]
Hi. Can you check which Cuda are you using in your environment?

**Comment by Blade6570** [comment]
It is Cuda 11.1. Otherwise, Mahti throws a lot of warnings about Pytorch's failure in utilizing GPUs.

**Comment by v-iashin** [comment]
I think I got the same error on Mahti. But now I don't remember what caused it. I think it was just a bug or something which I found by running the code without ddp. 

Merging this by squashing the commit history as the fork wasn't synced before creating a PR or something 🙂 .

**Comment by Blade6570** [comment]
Good to know. Something weird is going on in the Mahti. The proposed workaround in the DDP makes the training slow but will investigate in the coming weeks.

**Pull request merged**
